#!/bin/bash
username=sanghz
#############################################
#############################################
#############################################
#CWID=`xdotool getwindowfocus`
CWID=`xdotool getactivewindow`
WID=`xdotool search --name "Mozilla Firefox" | head -1`
WID2=`xdotool search --name "\- Chromium" | head -1`
if [ ! $WID ]; then WID=-1;fi
if [ ! $WID2 ]; then WID2=-1;fi
if [ $CWID -eq $WID -o $CWID -eq $WID2 ];then
	ibusIC=`sudo -u $username python /usr/local/bin/xdoibus.py`;ibusICnum=${ibusIC##*_};
	sleep 0.2
	case $1 in
		u)
			[ $ibusICnum != 1 ] && exit;
			xdotool key ctrl+shift+t
			;;
		d)
			[ $ibusICnum != 1 ] && exit;
			xdotool key ctrl+w
			;;
		r)
			[ $ibusICnum != 1 ] && exit;
			xdotool key ctrl+r
			;;
		t)
			[ $ibusICnum != 1 ] && exit;
			xdotool key ctrl+t
			;;
		y)
			[ $ibusICnum != 1 ] && exit;
			xdotool key ctrl+l ctrl+c Tab Tab
			;;
		gg)
			[ $ibusICnum != 1 ] && exit;
			xdotool key "Home"
			;;
		SHIFTg)
			[ $ibusICnum != 1 ] && exit;
			xdotool key "End"
			;;
		CTRL1)
			sudo -u $username firefox -new-tab https://arxiv.org/list/hep-ph/new &
			#xdotool key ctrl+t
			#xdotool key ctrl+l
			#xdotool type " https://arxiv.org/list/hep-ph/new"
			#xdotool key "Return"
			;;
		CTRL2)
			sudo -u $username firefox -new-tab http://www.sohu.com/ &
			;;
		CTRL3)
			sudo -u $username firefox -new-tab https://www.baidu.com/ &
			;;
	esac
	exit
fi

#############################################
#############################################
#############################################
WID=`xdotool search --name "Skype" | tail -1`
#CWID=`xdotool getwindowfocus`
CWID=`xdotool getactivewindow`
if [ ! $WID ]; then WID=-1;fi
if [ $CWID -eq $WID ];then
	sleep 0.2
	case $1 in
		CTRL1)
            xdotool click 3 mousemove_relative 0 55;
            sleep 0.1;
            xdotool click 1
            sleep 0.2;
            xdotool key ctrl+Tab
            xdotool key ctrl+Tab
            xdotool key ctrl+f
            sleep 0.1;
            xdotool type "Desktop"
            sleep 0.01;
            xdotool key "Return"
			;;
	esac
	exit
fi



#############################################
#############################################
#############################################
WID=`xdotool search --name "Oracle VM Virtualbox" | head -1`
#CWID=`xdotool getwindowfocus`
CWID=`xdotool getactivewindow`
if [ ! $WID ]; then WID=-1;fi
if [ $CWID -eq $WID ];then
	sleep 0.2
	case $1 in
		ALT1)
            xdotool type "11"
            xdotool key "Return"
			;;
		ALT2)
            xdotool type "22"
            xdotool key "Return"
			;;
		ALT3)
            xdotool type "33"
            xdotool key "Return"
			;;
		ALT4)
            xdotool type "44"
            xdotool key "Return"
			;;
	esac
	exit
fi
